#!/bin/bash

#
# Basic script to run ctags for PHP on a specific directory
#

if test "$1"
then
	cd "$1"
fi

echo "Running ctags."
echo "   --> cd ${PWD}"
echo "   --> ctags -R --languages=php --PHP-kinds=+cifd --tag-relative=yes"

ctags -R --languages=php --PHP-kinds=+cifd --tag-relative=yes

echo "Script has finished."
