#!/usr/bin/env bash

OSTYPE=`uname`

if [[ -d "$PWD/.ddev" ]]; then
  echo "exec php $@"
  ddev exec php $@
elif [[ $OSTYPE == "Darwin" ]]; then
  echo "herd php $@"
  herd php $@
else
  echo "/usr/bin/php $@"
  /usr/bin/php $@
fi
