#!/usr/bin/env bash

set -eu

if [ -z "$1" ]; then
	echo "You did not specify a database."
else
	echo "Dropping database if exists $1"
	mysql -udemo -p -e "DROP DATABASE IF EXISTS $1;"

	echo "Creating database $1"
	mysql -udemo -p -e "CREATE DATABASE $1"
fi
