#!/usr/bin/env bash

if [ -f /usr/bin/php7.4 ]; then
    /usr/bin/php7.4 $HOME/.config/composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer "$@"
else
    PHP_CS_FIXER_IGNORE_ENV=false php $HOME/.config/composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer "$@"
fi
